version: '3'

services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 18000:3306
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=douyin
      - MYSQL_PASSWORD=douyin123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  
  minio:
    image: minio/minio
    ports:
      - 18001:9000 # api 端口
      - 18002:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: douyin    #管理后台用户名
      MINIO_SECRET_KEY: douyin123 #管理后台密码，最小8个字符
    volumes:
      - ./pkg/data/:/data               #映射当前目录下的data目录至容器内/data目录
      - ./pkg/configs/minio/:/root/.minio     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always

  ffmpeg:
    image: jrottenberg/ffmpeg
    ports:
      - 18003:8080
    
  redis:
    image: redis
    container_name: redis7
    ports:
      - 6379:6379
    volumes:
      - ./datadir:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
