// Code generated by hertz generator.

package publish

import (
	"context"
	"offer_tiktok/pkg/errno"
	"offer_tiktok/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	publish "offer_tiktok/biz/model/basic/publish"
	service "offer_tiktok/biz/service/publish"
)

// PublishAction publish a video
//
// @router /douyin/publish/action/ [POST]
func PublishAction(ctx context.Context, c *app.RequestContext) {
	var err error

	var req publish.DouyinPublishActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(errno.ParamErr)
		c.JSON(consts.StatusBadRequest, publish.DouyinPublishActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
		return
	}
	err = service.NewPublishService(ctx, c).PublishAction(&req)

	resp := utils.BuildBaseResp(err)
	c.JSON(consts.StatusOK, publish.DouyinPublishActionResponse{
		StatusMsg:  resp.StatusMsg,
		StatusCode: resp.StatusCode,
	})
}

// PublishList get the video list of user
//
// @router /douyin/publish/list/ [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish.DouyinPublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewPublishService(ctx, c).PublishList(&req)
	if err != nil {
		bresp := utils.BuildBaseResp(err)
		resp.StatusCode = bresp.StatusCode
		resp.StatusMsg = bresp.StatusMsg
		c.JSON(consts.StatusOK, resp)
	}
	resp.StatusCode = errno.SuccessCode
	resp.StatusMsg = errno.SuccessMsg
	c.JSON(consts.StatusOK, resp)
}
