// Code generated by hertz generator.

package favorite

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	favorite "offer_tiktok/biz/model/interact/favorite"
)

// FavoriteAction .
// @router /douyin/publish/action [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.douyin_favorite_action_request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(favorite.douyin_favorite_action_response)

	c.JSON(consts.StatusOK, resp)
}

// FavoriteList .
// @router /douyin/publish/list [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.douyin_favorite_list_request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(favorite.douyin_favorite_list_response)

	c.JSON(consts.StatusOK, resp)
}
