// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	comment "offer_tiktok/biz/router/comment"
	favorite "offer_tiktok/biz/router/favorite"
	feed "offer_tiktok/biz/router/feed"
	message "offer_tiktok/biz/router/message"
	publish "offer_tiktok/biz/router/publish"
	relation "offer_tiktok/biz/router/relation"
	user "offer_tiktok/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	message.Register(r)

	relation.Register(r)

	comment.Register(r)

	favorite.Register(r)

	feed.Register(r)

	publish.Register(r)

	user.Register(r)

}
